{
 "title": "jiong_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Traffic Status Trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(\r\n  {job=\"nginx\"} \r\n  | pattern `<_> - - [<_>] \"<method> <uri> <_>\" <status> <size> <_>`\r\n  | status != \"-\" \r\n  [1m]\r\n)) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "nginx error",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(\r\n  {job=\"nginx\"} \r\n  | pattern `<_> - - [<_>] \"<method> <uri> <_>\" <status> <size> <_>`\r\n  | status =~ \"400|401|403|404|500|502|503\"\r\n  [5m]\r\n))"
    }
   ]
  },
  {
   "title": "Total Valid Logs (5m)",
   "type": "stat",
   "description": "Total Request Count (5m)",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (host) (count_over_time({job=\"storage-services\"} \r\n  |~ \"(?i)error|failed|timeout|denied\" \r\n  != \"info\" \r\n  != \"Failed to fetch domain sid\" \r\n  != \"messaging_dgm_get_unique failed\"\r\n  != \"latency=\" [5m]))"
    }
   ]
  },
  {
   "title": "nginx_error logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"storage-services\"}\r\n|~ \"(?i)error|failed|timeout|denied\""
    }
   ]
  },
  { "title": "스토리지", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Error by Protocol (5m)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (host) (count_over_time({job=\"storage-services\"} \r\n  != \"info\" \r\n  != \"Failed to fetch domain sid\" \r\n  != \"messaging_dgm_get_unique failed\"\r\n  != \"latency=\" [5m]))"
    }
   ]
  },
  {
   "title": "Storage Live Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"storage-services\"}"
    }
   ]
  },
  { "title": "서비스", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Critical System Alerts (15m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"docker\"} |~ \"(?i)ERROR|CRITICAL\" != \"level=info\" != \"level=debug\" != \"level=warn\" != \"portfolio-web-app\" != \"portfolio-web-jenkins-1\" [5m]))"
    }
   ]
  },
  {
   "title": "System Critical Logs (Filtered)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\"} \r\n|~ \"(?i)ERROR|CRITICAL\" \r\n!= \"level=info\" \r\n!= \"level=debug\" \r\n!= \"level=warn\" \r\n!= \"portfolio-web-app\" \r\n!= \"portfolio-web-jenkins-1\""
    }
   ]
  },
  {
   "title": "App Server Errors (5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"docker\"} \r\n  |~ \"portfolio-web-app\" \r\n  |~ \"(?i)error|failed\" \r\n  != \"latency=\" != \"query=\" [5m]))"
    }
   ]
  },
  {
   "title": "App Server Real-time Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\"} \r\n|~ \"portfolio-web-app\" \r\n|~ \"(?i)error|failed|flushing\" \r\n!= \"latency=\" != \"query=\""
    }
   ]
  },
  {
   "title": "Jenkins Build Failures (5m)",
   "type": "stat",
   "description": "Jenkins 빌드 실패 횟수",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"docker\"} |= \"portfolio-web-jenkins-1\" |= \"FAILURE\" != \"latency=\" != \"query=\" [5m]))"
    }
   ]
  },
  {
   "title": "Jenkins Build History (Recent)",
   "type": "logs",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\"} \r\n|= \"portfolio-web-jenkins-1\" \r\n!= \"failed to flush\" \r\n!= \"i/o timeout\" \r\n!= \"component=ingester\""
    }
   ]
  }
 ]
}