apiVersion: v2
name: promtail
version: 0.1.0
description: Promtail log agent DaemonSet for k8s cluster

dependencies:
  - name: promtail
    version: "6.16.6"
    repository: https://grafana.github.io/helm-charts
