grafana:
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    server:
      domain: jiun2.ddns.net
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: longhorn
  podAnnotations:
    sidecar.istio.io/inject: "false"
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
      jsonData:
        httpHeaderName1: X-Scope-OrgID

prometheus:
  prometheusSpec:
    retention: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

prometheus-node-exporter:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'null'
    receivers:
      - name: 'null'

kubeEtcd:
  enabled: true
  endpoints:
    - 20.20.20.241
    - 20.20.20.242
    - 20.20.20.243
  service:
    enabled: true
    port: 2381
    targetPort: 2381
  serviceMonitor:
    enabled: true
    scheme: http
    insecureSkipVerify: true
