image:
  repository: 905921696911.dkr.ecr.ap-northeast-2.amazonaws.com/portfolio-web
  tag: "7"
  pullPolicy: Always

replicaCount: 2

service:
  port: 3000


ingress:
  externalHost: jiun2.ddns.net
  internalHost: portfolio-web.internal
  path: /

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
