apiVersion: v2
name: loki-stack
version: 0.2.0
description: Loki log aggregation server + VirtualService

dependencies:
  - name: loki
    version: "6.30.1"
    repository: https://grafana.github.io/helm-charts
