---
- name: Deploy Promtail config to monitoring VMs
  hosts: monitoring-vms
  become: true
  tasks:
    - name: Promtail config 배포
      template:
        src: "promtail-{{ inventory_hostname }}.conf.j2"
        dest: /etc/promtail/config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Promtail 재시작
      service:
        name: promtail
        state: restarted
        enabled: yes
