apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: jenkins
    jsonPointers:
    - /data
  project: default
  source:
    repoURL: git@github.com:wownae-ct/infra-repo.git
    targetRevision: HEAD
    path: apps/jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
