apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-extras
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/wownae-ct/infra-repo.git
    targetRevision: HEAD
    path: apps/kiali
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
