---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: default
spec:
  encryptedData:
    access-key: AgAfYs279JkiQf+uMFkgfFYXm6VRW8rQhcbJTaaTZjp92lULy0P2LXO9ZWb+3JYiMH28o3xGA4in22D0niPkJtLeNGb/UXxdR6v+/26fGBWNK2iv3uxc6hgqo9bxm+so+cPDEVLv5iHswYvZQYJfn4N/8yjkEn98YZLrrtV2fhLraaSwus31zANCkiQNhNS87KfB3HoZhVumXbhHp91tdaaVICBzj+6qqQA8IjVkBxBk8HE/5mjTSAH0bdfG5LSEOJWXjXkXdCQ4tLqg4RteLSqxmwSfBcaLQl/B0vHjgd0+0rl3mHaJNCcaoUUJVKG8oWZyW2UyPnl3h5jf4sHQhK/NW3SKBJhgloKu5jXtUS3jYdCXu+iObPcHrtHtZ/P1/emIXQdF4pYfyvVnqg/51crUOPINee7Zq2DeLzieKHCy18mJE4YVzVxV+K5AZ9fpdNKbsC+F0M+wehRfx5Uhg7VBL90GEr0NGu21u3Y5LCvibyL/T5X5l/vo1AnlqBzTHrxVcAvdJr4VLmONxTb9zrdFBDqzvGfYI/AHqmeR2wXiW23JHpo2n8W5+YxtnCkXVnmTTNKmuPZaO1ZD/YwwZipSPorI6Ip1duZzosdm3bRKmS/fIVgNXPo54A4fIsjs+bRgS7uYSH/h0PDA4d5PTKg9D2pTPnUmysTyNfZWY7IpEUE3/DD0kOVIn2ncd5myFkOOBTT/q81l/Z8xvouIo2UBNULxuQ==
    secret-key: AgAiiE0Jn/o5tkQD1mEUnzDZtH7FwXHN18f5ZnwmgUsNA/sre0m0qTt5NsaK2MgW84/h15uhDSopDrzphMVw5VVBBF3NoBDxIRsHjITzh+qnjRJRvD9717chi96LADF6RafUEF8Hi/Rev0zW+oESJTCvRdZ9172m8jUmGkfQbwV2vNf923Uv4QvjKRI9v2vKnx7/cWz1wsGPcHZo6rnjKEm7e8q/rS8vfeQTL7GXVWziqtH9cO4Ndp9ntcEvQyYybuVLfbpT6AuCzFsblfaAC18pgD8YdKxa9eWv/PG9insDjPB9rFpj9l4EZnnlLGMEZSwEPvTCNcLk5NpehHLVanFca9QRAaMZyZNTZ+mow9pN/K1wkdqHHWPQYL4jBfCGJ2CUn+xF2GDb9S+3gb5DCWkBkQZftAedPt1UD7BK/Yw8XAkry0o0Sbspjf0TXANRy1n/r7Wv5QTRFxjb3SxdGXeQJ0OoF1aXh/0ASdsjfUbUlm7KDZPu7SWqJyyG9+CdT+7QHmN154O7n/YZYeIe/jQYM/wC9tN96OydqUWbUHXAq2L6C45amgwV38N5CGT7VRK7eNSlJaFjoL56eIN9pgSsKVyV/epvP3PzdwuPfcABvygGk8hOnmDjJzB1q4MiWeG1gbNFuFKrlFLU92YIiuVilOq5vqPPPr3Z0Wv+kTBU7JSbyAi+2kT82BucVS2KcHuaikcTst7ryI8EFyyOQCainPRODtwAzXzeIeo4w1Qr72VxAkz968dn
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: default
    type: Opaque
