---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    access-key: AgCK3n98pHj0Fn5KOeLEi/CYdt/a+owq7p4Vrb5oYSuEpIKX90LbnQTxhiUwY7uconIuKNMH0n4YRudXda5Bjc+tQm0FFgpGIG8HaliGCKR/DW/jtCjA0nV403t1p1gT9EwZM7CgxnKMZUjND9gZMk+nmvl3CIscaP/xnyRdQTX8ZFlnHhSPSI7ycI0Ou12X03MWubm9uPwlExjld7+Een1Zg+hlbQdtQls1Bt4GRQ4MfRV0zMprdGcDsSeIYJcg9c4fjXmmTpzTg26KQVxFX0tH9VnzOwVta4J4iOTQSwh4quT34A0fv+/LpiiuvXQLCw9QUOe0efF9p5cEeVM0TkcMPbj3a+poBmqH+IqR7hnTW1Ibxvj0WDS7Nf6MsXSugIyt2x3nYYp2RVt8ZI0hol4bbVHPmhJ718TbMgFnNc6fA62tm28UqYz3AXXwGDkJ1VfJUm+2Dxhkw/WygSxqnrg/W71nH0fB7Hz/9PmQ7svrBdjvfoqZGtXBCoB+pFM2K6kAk8TJEhKQqAU0Gk44TaOVMqORYem+Z4sci2WprLx/EiDB/DRLxX8tKKKMqX37dUCHKdcPUZQk7uE2Bn2Pru8/ue8Nm20yAhtzsYPVsvIKAU3TM7nuj7KiRJWuj6O5l2NyombHD0fbumiEPK02QrXMdZm02fygyU98zYNv/WWskSW2Z4f5hMIn19n9LRYVkiDFjWrJQ+O5RGQXtSQ+OJD0oKEkQg==
    secret-key: AgBIYEs4o9pTgSPj2nA7TuKd66MnKgU63l+bp1sHF23JW6xibnUUFZ//QsVyjXo/iqFqhRNzaIo3LqaSsAqPSVMS4T/qDidub2OXe4nUHeFyPX8Z7rNqwSWNr3bHOKnpmfOZfnmA9AsKF0wvenDoaJntkKL5X03hIE902jk2C1iynS8uJHGfUNPt66UkKjfBFo+DktNFH/B44LeWs8Dy9IprmflCBf9PjLgaIMwF/KmFWEkjgIRV65b2/Jj2SjOxSd77xnRQxGouUSdmgnLOvjfJ2/F4ecS0+oBDHTAmBa8MMbrWk1ngphPgc0r/xpvzNcFqyOKeN15aO44XOApDkKNrrxojrB5I+iUlYhPhh6J+lzy8rxkCqIi+WSA+bRDZfFBCsgYNZ8iSuElKezFBaZZfHR4XdiCs6p+kRU3iv8+JFfkD0F2b5ND5QfdXAafAC8IXaKcykR4vbDAO5ZkS6TqCopl+fQoQ88gZUaZW845gLZZhMA6ztYpd8nvcnrOer99osoP9py/TRCFHn2ZSI9uLOdgDW9cUmO03l2KYtxs+oSoSEoWy5tbIAcd4aftq/ek32hOWtHEgTtrPecSNrUf7NJBp9mHKoZKW/cH4B2MXcnWNWBChRwq8M/otpFzPgn8gsMbT/SKfRmPfV5U1AM2zz1rSleH4VBFat04Hrqvn83YgtvtkQ1WpHIbwMqhaRMDucNZw7Rs1N8b3XvapNY971/q5Jb/pSM6YzIXyxk/qo3eKImHpZsaN
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
    type: Opaque
