{
 "title": "portfolio-web metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "응답 시간 p99/p95/p50 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=~\"portfolio-web.*\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=~\"portfolio-web.*\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_service=~\"portfolio-web.*\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": " 5xx 에러율 (rate 1m)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service=~\"portfolio-web.*\", response_code=~\"5..\"}[1m]))\r\n/\r\nsum(rate(istio_requests_total{destination_service=~\"portfolio-web.*\"}[1m]))",
     "legendFormat": "5xx 에러율"
    }
   ]
  },
  {
   "title": "HTTP 요청 수 (rate 1m)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service=~\"portfolio-web.*\"}[1m])) by (response_code)",
     "legendFormat": "{{`{{response_code}}`}}"
    }
   ]
  }
 ]
}