apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: monitoring
spec:
  gateways:
  - istio-system/internal-gateway
  hosts:
  - "grafana.internal"
  - "grafana.jiun2-internal.net"
  http:
  - match:
    - headers:
        upgrade:
          exact: websocket
    route:
    - destination:
        host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
        port:
          number: 80
    timeout: 300s
  - route:
    - destination:
        host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
        port:
          number: 80
