---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-datasource-loki-secret
  namespace: monitoring
spec:
  encryptedData:
    httpHeaderValue1: AgAb3me2B4xiVxB1BuQ/NxKup7I66BJSv8foDMAdUcMTBy4U3xHxNTKDuYwyjk5l/8wd/Ogv+J9GfegTf/IZMI7jjnqgz4b5E1FgY+cN2nLbqKFBp1Uu/Saq1UZSLYDCPeU9Q4b5lOSff50XkvTRLOSUm1t28c29tmazeOGKCzybiNbc+igNHneDqMQrfDm3kIwKNtQmz6yVpAtqCLpol99Rf66Aard7pSRWtbKu4QnP6HH8JgPEPsU0jrhKMO0QdrpoVX/cL0yux9CuvkTezYLK5T5GmcEPRiFBU9CYSV6LdSfoomBpNjq4/p/VQwAKNyochLaJm5nRSA6cA9P9ieC07JFRgLTsVoM35qlqLf2xQB5DCVz0L/t+GNx3elD3tKHzdGtaQQaRIqmhWVvXr/ZxjojCSa1by6udZNMtGpOcSbK+qegD5G1o/iRYxRUtLiJ4XwWgQND7ZEnQZ7dRCBW7SxI6ETQtDJcc3X464je26AtFBBV15azy6CLRK5HK3w6nlLFgeyvFmO/h+LBozZ2MIEJRkze37hZVhtA4FvWHMGsl9/D/M5TsWdlUjZECzZch9Imo3BfxD9gHrL/Uq6HDD8wJTmwDXP6v1OUYdfuaZ2S9QraxGLWb5+s122UT2v2HZ1veP24/jR+zR/B1fBc35yY6rt+CySFfKdpC4+xg7oynTUm37dkWKCV8/Qzj9VOG8kQ=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-datasource-loki-secret
      namespace: monitoring
