---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAsYB9nBr8ilJIlBQ3zqQZ9JpAqqFXLkpCfNRot1rfchnr/SaBAOaWGO4lhjUVGk/m1pdedc4pwjA+Ta/kwEX1xQMK8uxzIZeaLIDA1NRYelSI/sTSYNuUxjxxHx6VaJ5auVCR7bnkbtllvRw1tspMIXhEw54N2MuuzcPYkbx+auyksV+FsFLFUhl1ST5mhmahaXD6Ra9V0D73QPT0uYSWaTzL9KOAYfvPDTZsjwxCQtBFdLT22IwG0fgq1LozlpgrS+NWWnv0NHRsiHgD0GOz8+LxGw+fyNcbQoLdKfjXLnGHvY4bLfsIqMOBHYB0PX/vnUH6y6XVwflThHIz+RE7xSrgLHaLyvUgaP3jcRReEa285vUNpWUo+hdAWbQ2LG/xoOEL6KbeZCf9u8/O6GSX7AxKyEA86ixr2h1Qn3BeOP+nNoQlg8BvkDM4vd4wxTZOTq6PpAlSLYQTi1xdxH5mw97fu9Ub1NlDxD/1m0mdb94BKp1TGPW627I7qYohDGYQ8CA10IidBJOaTHPuMkHXwtmZV1VO/QX2GgYdfSgeHa0tLCD7w0/+9vcMo+0h/0jBw1nlrTpjtpsjMLjJqC1dbAcHSLEO4OkXejIHsW+FvdD9xHlagFUD8B5YhproF1rJVcTeStgT6I1It4Y6sHP9QOXZSiMOzqEch+8vqQdE7vZFSQmJs9/ON2DwgiCd0qxnRfqZURb3HoLALVl8x
    admin-user: AgA1fnNySlVbVdHsKcGJRV4MyadhGyy33F3EY6pFdkAcjgRNKmObQAxScCk5byr65TLUt8Kl9ZZfGazytwfhvxSCOivMiZqnTRGEZdsiZW9BukbTWP23dwvQJdsjzg5Zjk0AI2HkANjKQhLm/nfPqnpuE60IsgfFQ2uMQ2HQNoQRuxP7qBhUhVRM/IWv/xkMFuqAkC0GdMf032Tej49I/YlpX6iiUHy2uG9Y93e5Jf8ZHwnJ5sDWx+ExKjm1KYu7Y/Hz3LaMzMN1rAnUYBOBdwLhtdrXvC3VWJLV01DrZt2X6758W02DThL2LKMmvkZgCb6vi7rRhURdBBXoDIU53bIfnU2L3dNDbyFIQPeHJu4QQ+LhG6gEbggshYp/hRN88nVgBJgr7PnzGNFuZJgDx3xwZdvoeTiF3hGpur8xActr0g4HmHNgHMkZJC2j6FCU89jcJv1E5TUzZUnYu+pYEro+73Bkgjd3heViNYW1I5RN8pbglpTnrm/RZf3euw5mJ8DIHfDo7t9Y3f1ubuyRTxfEGIW3cygn0rlbkJ9ipWzJ5AT4ANurl68sI6bMjXGr7pfoWP0lIGcEhBH0ditP4j7LrOc/qChGC1Y0j9mAMg+L2OT2uFCVXQSh+UH4kCkpoxiNyXTdYfTC/iXZqE28OIVLi0PANK5NOapkg6C7y5Z5zGwvp2uxnj/qUKzmzI4+FExdYtP7cw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
